#' Remove all artifacts generated by scripts
#'
#' Removes all output files generated by scripts in the pipeline, including
#' intermediate files. This provides a complete clean of generated artifacts.
#' The pipeline can be regenerated by running run() again.
#'
#' @return Character vector of file paths that were actually removed
#' @export
#' @examples
#' \dontrun{
#' # Remove all generated files
#' removed_files <- clean()
#' }
clean <- function() {
  # Parse all scripts to get dependencies
  dependencies <- bakepipe:::parse()

  # If no scripts found, return empty vector
  if (length(dependencies) == 0) {
    character(0)
  }

  # Collect all outputs
  all_outputs <- character(0)

  for (script_info in dependencies) {
    all_outputs <- c(all_outputs, script_info$outputs)
  }

  # Remove duplicates
  all_outputs <- unique(all_outputs)

  # Only try to remove files that actually exist
  existing_files <- all_outputs[file.exists(all_outputs)]

  # Remove the files
  removed_files <- character(0)
  for (file_path in existing_files) {
    if (file.remove(file_path)) {
      removed_files <- c(removed_files, file_path)
    }
  }

  removed_files
}