#' Remove all artifacts generated by scripts
#'
#' Removes all output files generated by scripts in the pipeline, including
#' intermediate files. This provides a complete clean of generated artifacts.
#' The pipeline can be regenerated by running run() again.
#'
#' @return Character vector of file paths that were actually removed
#' @export
#' @examples
#' \dontrun{
#' # Remove all generated files
#' removed_files <- clean()
#' }
clean <- function() {
  # Parse all scripts to get dependencies
  dependencies <- bakepipe:::parse()

  # If no scripts found, return empty vector
  if (length(dependencies$scripts) == 0) {
    return(character(0))
  }

  # Get all outputs from the top-level outputs list
  all_outputs <- dependencies$outputs

  # Only try to remove files that actually exist
  existing_files <- all_outputs[file.exists(all_outputs)]

  # Remove the files
  removed_files <- character(0)
  for (file_path in existing_files) {
    if (file.remove(file_path)) {
      removed_files <- c(removed_files, file_path)
    }
  }

  removed_files
}